/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CspReportRouteImport } from './routes/csp-report'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DevSplatRouteImport } from './routes/dev/$'
import { Route as DevChar123Char125DotmdRouteImport } from './routes/dev/{$}[.]md'
import { Route as DevChar123Char125DottxtRouteImport } from './routes/dev/{$}[.]txt'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsChar123Char125DottxtRouteImport } from './routes/docs/{$}[.]txt'
import { Route as OgSplatRouteImport } from './routes/og/$'
import { Route as ReferenceSplatRouteImport } from './routes/reference/$'
import { Route as ApiChatSiteRouteImport } from './routes/api/chat.$site'
import { Route as ApiMcpSiteRouteImport } from './routes/api/mcp.$site'
import { Route as ApiSearchSiteRouteImport } from './routes/api/search.$site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CspReportRoute = CspReportRouteImport.update({
  id: '/csp-report',
  path: '/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSplatRoute = DevSplatRouteImport.update({
  id: '/dev/$',
  path: '/dev/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevChar123Char125DotmdRoute = DevChar123Char125DotmdRouteImport.update({
  id: '/dev/{$}.md',
  path: '/dev/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DevChar123Char125DottxtRoute = DevChar123Char125DottxtRouteImport.update({
  id: '/dev/{$}.txt',
  path: '/dev/{$}.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DottxtRoute =
  DocsChar123Char125DottxtRouteImport.update({
    id: '/docs/{$}.txt',
    path: '/docs/{$}.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceSplatRoute = ReferenceSplatRouteImport.update({
  id: '/reference/$',
  path: '/reference/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSiteRoute = ApiChatSiteRouteImport.update({
  id: '/api/chat/$site',
  path: '/api/chat/$site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSiteRoute = ApiMcpSiteRouteImport.update({
  id: '/api/mcp/$site',
  path: '/api/mcp/$site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchSiteRoute = ApiSearchSiteRouteImport.update({
  id: '/api/search/$site',
  path: '/api/search/$site',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dev/$': typeof DevSplatRoute
  '/dev/{$}.md': typeof DevChar123Char125DotmdRoute
  '/dev/{$}.txt': typeof DevChar123Char125DottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/docs/{$}.txt': typeof DocsChar123Char125DottxtRoute
  '/og/$': typeof OgSplatRoute
  '/reference/$': typeof ReferenceSplatRoute
  '/api/chat/$site': typeof ApiChatSiteRoute
  '/api/mcp/$site': typeof ApiMcpSiteRoute
  '/api/search/$site': typeof ApiSearchSiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dev/$': typeof DevSplatRoute
  '/dev/{$}.md': typeof DevChar123Char125DotmdRoute
  '/dev/{$}.txt': typeof DevChar123Char125DottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/docs/{$}.txt': typeof DocsChar123Char125DottxtRoute
  '/og/$': typeof OgSplatRoute
  '/reference/$': typeof ReferenceSplatRoute
  '/api/chat/$site': typeof ApiChatSiteRoute
  '/api/mcp/$site': typeof ApiMcpSiteRoute
  '/api/search/$site': typeof ApiSearchSiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dev/$': typeof DevSplatRoute
  '/dev/{$}.md': typeof DevChar123Char125DotmdRoute
  '/dev/{$}.txt': typeof DevChar123Char125DottxtRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/docs/{$}.txt': typeof DocsChar123Char125DottxtRoute
  '/og/$': typeof OgSplatRoute
  '/reference/$': typeof ReferenceSplatRoute
  '/api/chat/$site': typeof ApiChatSiteRoute
  '/api/mcp/$site': typeof ApiMcpSiteRoute
  '/api/search/$site': typeof ApiSearchSiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/csp-report'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dev/$'
    | '/dev/{$}.md'
    | '/dev/{$}.txt'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/docs/{$}.txt'
    | '/og/$'
    | '/reference/$'
    | '/api/chat/$site'
    | '/api/mcp/$site'
    | '/api/search/$site'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/csp-report'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dev/$'
    | '/dev/{$}.md'
    | '/dev/{$}.txt'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/docs/{$}.txt'
    | '/og/$'
    | '/reference/$'
    | '/api/chat/$site'
    | '/api/mcp/$site'
    | '/api/search/$site'
  id:
    | '__root__'
    | '/'
    | '/csp-report'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dev/$'
    | '/dev/{$}.md'
    | '/dev/{$}.txt'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/docs/{$}.txt'
    | '/og/$'
    | '/reference/$'
    | '/api/chat/$site'
    | '/api/mcp/$site'
    | '/api/search/$site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CspReportRoute: typeof CspReportRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DevSplatRoute: typeof DevSplatRoute
  DevChar123Char125DotmdRoute: typeof DevChar123Char125DotmdRoute
  DevChar123Char125DottxtRoute: typeof DevChar123Char125DottxtRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  DocsChar123Char125DottxtRoute: typeof DocsChar123Char125DottxtRoute
  OgSplatRoute: typeof OgSplatRoute
  ReferenceSplatRoute: typeof ReferenceSplatRoute
  ApiChatSiteRoute: typeof ApiChatSiteRoute
  ApiMcpSiteRoute: typeof ApiMcpSiteRoute
  ApiSearchSiteRoute: typeof ApiSearchSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp-report': {
      id: '/csp-report'
      path: '/csp-report'
      fullPath: '/csp-report'
      preLoaderRoute: typeof CspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$': {
      id: '/dev/$'
      path: '/dev/$'
      fullPath: '/dev/$'
      preLoaderRoute: typeof DevSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/{$}.md': {
      id: '/dev/{$}.md'
      path: '/dev/{$}.md'
      fullPath: '/dev/{$}.md'
      preLoaderRoute: typeof DevChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/{$}.txt': {
      id: '/dev/{$}.txt'
      path: '/dev/{$}.txt'
      fullPath: '/dev/{$}.txt'
      preLoaderRoute: typeof DevChar123Char125DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.txt': {
      id: '/docs/{$}.txt'
      path: '/docs/{$}.txt'
      fullPath: '/docs/{$}.txt'
      preLoaderRoute: typeof DocsChar123Char125DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/$': {
      id: '/reference/$'
      path: '/reference/$'
      fullPath: '/reference/$'
      preLoaderRoute: typeof ReferenceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$site': {
      id: '/api/chat/$site'
      path: '/api/chat/$site'
      fullPath: '/api/chat/$site'
      preLoaderRoute: typeof ApiChatSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/$site': {
      id: '/api/mcp/$site'
      path: '/api/mcp/$site'
      fullPath: '/api/mcp/$site'
      preLoaderRoute: typeof ApiMcpSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/$site': {
      id: '/api/search/$site'
      path: '/api/search/$site'
      fullPath: '/api/search/$site'
      preLoaderRoute: typeof ApiSearchSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CspReportRoute: CspReportRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DevSplatRoute: DevSplatRoute,
  DevChar123Char125DotmdRoute: DevChar123Char125DotmdRoute,
  DevChar123Char125DottxtRoute: DevChar123Char125DottxtRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  DocsChar123Char125DottxtRoute: DocsChar123Char125DottxtRoute,
  OgSplatRoute: OgSplatRoute,
  ReferenceSplatRoute: ReferenceSplatRoute,
  ApiChatSiteRoute: ApiChatSiteRoute,
  ApiMcpSiteRoute: ApiMcpSiteRoute,
  ApiSearchSiteRoute: ApiSearchSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
