/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CspReportRouteImport } from './../node_modules/@joeblew999/remy-ui/src/app-routes/csp-report'
import { Route as RobotsChar91DotChar93txtRouteImport } from './../node_modules/@joeblew999/remy-ui/src/parts/seo-routes/routes/robots[.]txt'
import { Route as SitemapChar91DotChar93xmlRouteImport } from './../node_modules/@joeblew999/remy-ui/src/parts/seo-routes/routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CspReportRoute = CspReportRouteImport.update({
  id: '/csp-report',
  path: '/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsChar91DotChar93txtRoute =
  RobotsChar91DotChar93txtRouteImport.update({
    id: '/robots.txt',
    path: '/robots.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapChar91DotChar93xmlRoute =
  SitemapChar91DotChar93xmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/csp-report' | '/robots.txt' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/csp-report' | '/robots.txt' | '/sitemap.xml'
  id: '__root__' | '/' | '/csp-report' | '/robots.txt' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CspReportRoute: typeof CspReportRoute
  RobotsChar91DotChar93txtRoute: typeof RobotsChar91DotChar93txtRoute
  SitemapChar91DotChar93xmlRoute: typeof SitemapChar91DotChar93xmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp-report': {
      id: '/csp-report'
      path: '/csp-report'
      fullPath: '/csp-report'
      preLoaderRoute: typeof CspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsChar91DotChar93txtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapChar91DotChar93xmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CspReportRoute: CspReportRoute,
  RobotsChar91DotChar93txtRoute: RobotsChar91DotChar93txtRoute,
  SitemapChar91DotChar93xmlRoute: SitemapChar91DotChar93xmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
