/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormatsRouteImport } from './routes/formats'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDemoRouteImport } from './routes/app.demo'
import { Route as AppLocationRouteImport } from './routes/app.location'
import { Route as TimeZonesSplatRouteImport } from './routes/time-zones.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatsRoute = FormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemoRoute = AppDemoRouteImport.update({
  id: '/app/demo',
  path: '/app/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLocationRoute = AppLocationRouteImport.update({
  id: '/app/location',
  path: '/app/location',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeZonesSplatRoute = TimeZonesSplatRouteImport.update({
  id: '/time-zones/$',
  path: '/time-zones/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formats': typeof FormatsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/demo': typeof AppDemoRoute
  '/app/location': typeof AppLocationRoute
  '/time-zones/$': typeof TimeZonesSplatRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formats': typeof FormatsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/demo': typeof AppDemoRoute
  '/app/location': typeof AppLocationRoute
  '/time-zones/$': typeof TimeZonesSplatRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formats': typeof FormatsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/demo': typeof AppDemoRoute
  '/app/location': typeof AppLocationRoute
  '/time-zones/$': typeof TimeZonesSplatRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formats'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/demo'
    | '/app/location'
    | '/time-zones/$'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formats'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/demo'
    | '/app/location'
    | '/time-zones/$'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/formats'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/demo'
    | '/app/location'
    | '/time-zones/$'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormatsRoute: typeof FormatsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AppDemoRoute: typeof AppDemoRoute
  AppLocationRoute: typeof AppLocationRoute
  TimeZonesSplatRoute: typeof TimeZonesSplatRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formats': {
      id: '/formats'
      path: '/formats'
      fullPath: '/formats'
      preLoaderRoute: typeof FormatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/demo': {
      id: '/app/demo'
      path: '/app/demo'
      fullPath: '/app/demo'
      preLoaderRoute: typeof AppDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/location': {
      id: '/app/location'
      path: '/app/location'
      fullPath: '/app/location'
      preLoaderRoute: typeof AppLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-zones/$': {
      id: '/time-zones/$'
      path: '/time-zones/$'
      fullPath: '/time-zones/$'
      preLoaderRoute: typeof TimeZonesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormatsRoute: FormatsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AppDemoRoute: AppDemoRoute,
  AppLocationRoute: AppLocationRoute,
  TimeZonesSplatRoute: TimeZonesSplatRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
