/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CspReportRouteImport } from './routes/csp-report'
import { Route as FormatsRouteImport } from './routes/formats'
import { Route as RobotsChar91DotChar93txtRouteImport } from './../packages/ui/src/parts/seo-routes/routes/robots[.]txt'
import { Route as SitemapChar91DotChar93xmlRouteImport } from './../packages/ui/src/parts/seo-routes/routes/sitemap[.]xml'
import { Route as ApiDotsplatRouteImport } from './routes/api.$'
import { Route as AppDotindexRouteImport } from './routes/app.index'
import { Route as AppDotaccountRouteImport } from './routes/app.account'
import { Route as AppDotaskRouteImport } from './routes/app.ask'
import { Route as AppDotclockRouteImport } from './routes/app.clock'
import { Route as AppDotdemoRouteImport } from './routes/app.demo'
import { Route as AppDotformatsRouteImport } from './routes/app.formats'
import { Route as AppDotlocationRouteImport } from './routes/app.location'
import { Route as AppDotsettingsRouteImport } from './routes/app.settings'
import { Route as DocsDotsplatRouteImport } from './routes/docs.$'
import { Route as TimeZonesDotsplatRouteImport } from './../packages/ui/src/parts/time-zones/routes/time-zones.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CspReportRoute = CspReportRouteImport.update({
  id: '/csp-report',
  path: '/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatsRoute = FormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsChar91DotChar93txtRoute =
  RobotsChar91DotChar93txtRouteImport.update({
    id: '/robots.txt',
    path: '/robots.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapChar91DotChar93xmlRoute =
  SitemapChar91DotChar93xmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDotsplatRoute = ApiDotsplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotindexRoute = AppDotindexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotaccountRoute = AppDotaccountRouteImport.update({
  id: '/app/account',
  path: '/app/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotaskRoute = AppDotaskRouteImport.update({
  id: '/app/ask',
  path: '/app/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotclockRoute = AppDotclockRouteImport.update({
  id: '/app/clock',
  path: '/app/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotdemoRoute = AppDotdemoRouteImport.update({
  id: '/app/demo',
  path: '/app/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotformatsRoute = AppDotformatsRouteImport.update({
  id: '/app/formats',
  path: '/app/formats',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotlocationRoute = AppDotlocationRouteImport.update({
  id: '/app/location',
  path: '/app/location',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDotsettingsRoute = AppDotsettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotsplatRoute = DocsDotsplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeZonesDotsplatRoute = TimeZonesDotsplatRouteImport.update({
  id: '/time-zones/$',
  path: '/time-zones/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/formats': typeof FormatsRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
  '/api/$': typeof ApiDotsplatRoute
  '/app/account': typeof AppDotaccountRoute
  '/app/ask': typeof AppDotaskRoute
  '/app/clock': typeof AppDotclockRoute
  '/app/demo': typeof AppDotdemoRoute
  '/app/formats': typeof AppDotformatsRoute
  '/app/location': typeof AppDotlocationRoute
  '/app/settings': typeof AppDotsettingsRoute
  '/docs/$': typeof DocsDotsplatRoute
  '/time-zones/$': typeof TimeZonesDotsplatRoute
  '/app/': typeof AppDotindexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/formats': typeof FormatsRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
  '/api/$': typeof ApiDotsplatRoute
  '/app/account': typeof AppDotaccountRoute
  '/app/ask': typeof AppDotaskRoute
  '/app/clock': typeof AppDotclockRoute
  '/app/demo': typeof AppDotdemoRoute
  '/app/formats': typeof AppDotformatsRoute
  '/app/location': typeof AppDotlocationRoute
  '/app/settings': typeof AppDotsettingsRoute
  '/docs/$': typeof DocsDotsplatRoute
  '/time-zones/$': typeof TimeZonesDotsplatRoute
  '/app': typeof AppDotindexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csp-report': typeof CspReportRoute
  '/formats': typeof FormatsRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
  '/api/$': typeof ApiDotsplatRoute
  '/app/account': typeof AppDotaccountRoute
  '/app/ask': typeof AppDotaskRoute
  '/app/clock': typeof AppDotclockRoute
  '/app/demo': typeof AppDotdemoRoute
  '/app/formats': typeof AppDotformatsRoute
  '/app/location': typeof AppDotlocationRoute
  '/app/settings': typeof AppDotsettingsRoute
  '/docs/$': typeof DocsDotsplatRoute
  '/time-zones/$': typeof TimeZonesDotsplatRoute
  '/app/': typeof AppDotindexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/csp-report'
    | '/formats'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/$'
    | '/app/account'
    | '/app/ask'
    | '/app/clock'
    | '/app/demo'
    | '/app/formats'
    | '/app/location'
    | '/app/settings'
    | '/docs/$'
    | '/time-zones/$'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/csp-report'
    | '/formats'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/$'
    | '/app/account'
    | '/app/ask'
    | '/app/clock'
    | '/app/demo'
    | '/app/formats'
    | '/app/location'
    | '/app/settings'
    | '/docs/$'
    | '/time-zones/$'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/csp-report'
    | '/formats'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/$'
    | '/app/account'
    | '/app/ask'
    | '/app/clock'
    | '/app/demo'
    | '/app/formats'
    | '/app/location'
    | '/app/settings'
    | '/docs/$'
    | '/time-zones/$'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CspReportRoute: typeof CspReportRoute
  FormatsRoute: typeof FormatsRoute
  RobotsChar91DotChar93txtRoute: typeof RobotsChar91DotChar93txtRoute
  SitemapChar91DotChar93xmlRoute: typeof SitemapChar91DotChar93xmlRoute
  ApiDotsplatRoute: typeof ApiDotsplatRoute
  AppDotaccountRoute: typeof AppDotaccountRoute
  AppDotaskRoute: typeof AppDotaskRoute
  AppDotclockRoute: typeof AppDotclockRoute
  AppDotdemoRoute: typeof AppDotdemoRoute
  AppDotformatsRoute: typeof AppDotformatsRoute
  AppDotlocationRoute: typeof AppDotlocationRoute
  AppDotsettingsRoute: typeof AppDotsettingsRoute
  DocsDotsplatRoute: typeof DocsDotsplatRoute
  TimeZonesDotsplatRoute: typeof TimeZonesDotsplatRoute
  AppDotindexRoute: typeof AppDotindexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp-report': {
      id: '/csp-report'
      path: '/csp-report'
      fullPath: '/csp-report'
      preLoaderRoute: typeof CspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formats': {
      id: '/formats'
      path: '/formats'
      fullPath: '/formats'
      preLoaderRoute: typeof FormatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsChar91DotChar93txtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapChar91DotChar93xmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppDotindexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/account': {
      id: '/app/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppDotaccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/app/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppDotaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clock': {
      id: '/app/clock'
      path: '/app/clock'
      fullPath: '/app/clock'
      preLoaderRoute: typeof AppDotclockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/demo': {
      id: '/app/demo'
      path: '/app/demo'
      fullPath: '/app/demo'
      preLoaderRoute: typeof AppDotdemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/formats': {
      id: '/app/formats'
      path: '/app/formats'
      fullPath: '/app/formats'
      preLoaderRoute: typeof AppDotformatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/location': {
      id: '/app/location'
      path: '/app/location'
      fullPath: '/app/location'
      preLoaderRoute: typeof AppDotlocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppDotsettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-zones/$': {
      id: '/time-zones/$'
      path: '/time-zones/$'
      fullPath: '/time-zones/$'
      preLoaderRoute: typeof TimeZonesDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CspReportRoute: CspReportRoute,
  FormatsRoute: FormatsRoute,
  RobotsChar91DotChar93txtRoute: RobotsChar91DotChar93txtRoute,
  SitemapChar91DotChar93xmlRoute: SitemapChar91DotChar93xmlRoute,
  ApiDotsplatRoute: ApiDotsplatRoute,
  AppDotaccountRoute: AppDotaccountRoute,
  AppDotaskRoute: AppDotaskRoute,
  AppDotclockRoute: AppDotclockRoute,
  AppDotdemoRoute: AppDotdemoRoute,
  AppDotformatsRoute: AppDotformatsRoute,
  AppDotlocationRoute: AppDotlocationRoute,
  AppDotsettingsRoute: AppDotsettingsRoute,
  DocsDotsplatRoute: DocsDotsplatRoute,
  TimeZonesDotsplatRoute: TimeZonesDotsplatRoute,
  AppDotindexRoute: AppDotindexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
